import User from '../models/User.js';
import logger from '../config/logger.js';
import { ROLES } from '../config/constants.js';

export const DEMO_EXPERTS = [
  {
    name: 'Dr. Ramesh Chandra Patel',
    email: 'expert.ramesh@kissansarthi.in',
    password: 'Password@123',
    role: ROLES.EXPERT,
    phone: '+91 98234 11001',
    city: 'Pune',
    state: 'Maharashtra',
    isVerified: true,
    isActive: true,
    verificationStatus: 'verified',
    availableForConsultation: true,
    availability: 'online',
    consultationFee: 99,
    experienceYears: 14,
    yearsExperience: 14,
    rating: 4.9,
    reviewsCount: 38,
    totalConsultations: 142,
    qualifications: [
      'Ph.D. in Soil Science & Agricultural Chemistry — MPKV Rahuri',
      'M.Sc. Agriculture (Soil Fertility) — IARI New Delhi',
      'ICAR Certified Senior Soil Specialist',
    ],
    expertise: ['Soil Chemistry', 'NPK Prescription', 'Precision Agriculture', 'Saline Soil Reclamation'],
    specializations: ['Soil Chemistry', 'NPK Prescription', 'Precision Agriculture', 'Saline Soil Reclamation'],
    languagesSpoken: ['Hindi', 'Marathi', 'English'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RameshPatel&backgroundColor=c0aede',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RameshPatel&backgroundColor=c0aede',
    profilePhotoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=RameshPatel&backgroundColor=c0aede',
    credentialDocUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    bio: 'Senior Agricultural Scientist with 14+ years advising over 3,000 progressive farmers across Maharashtra and Gujarat. Specialized in soil fertility restoration, micronutrient deficiencies (Zinc, Boron), and high-yield crop rotation schedules.',
    reviews: [
      {
        farmerName: 'Balwant Patil (Sangli)',
        rating: 5,
        comment: 'Dr. Ramesh gave precise gypsum and zinc sulphate dosages for my sugarcane crop. Soil salinity dropped noticeably and shoot germination increased!',
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
      },
      {
        farmerName: 'Dhyan Singh (Nashik)',
        rating: 5,
        comment: 'Very patient explanation in Marathi. Solved our yellow leaf nitrogen deficiency within 48 hours.',
        date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    name: 'Dr. Sunita Sharma',
    email: 'expert.sunita@kissansarthi.in',
    password: 'Password@123',
    role: ROLES.EXPERT,
    phone: '+91 98234 11002',
    city: 'Ludhiana',
    state: 'Punjab',
    isVerified: true,
    isActive: true,
    verificationStatus: 'verified',
    availableForConsultation: true,
    availability: 'online',
    consultationFee: 149,
    experienceYears: 11,
    yearsExperience: 11,
    rating: 4.95,
    reviewsCount: 47,
    totalConsultations: 189,
    qualifications: [
      'Ph.D. in Plant Pathology — Punjab Agricultural University (PAU), Ludhiana',
      'M.Sc. Mycology & Plant Pathology — GBPUAT Pantnagar',
      'Fellow of the Indian Phytopathological Society',
    ],
    expertise: ['Plant Pathology', 'Fungal Blight Control', 'Pest Management (IPM)', 'Viral Mosaic Virus'],
    specializations: ['Plant Pathology', 'Fungal Blight Control', 'Pest Management (IPM)', 'Viral Mosaic Virus'],
    languagesSpoken: ['Hindi', 'Punjabi', 'English'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SunitaSharma&backgroundColor=b6e3f4',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SunitaSharma&backgroundColor=b6e3f4',
    profilePhotoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SunitaSharma&backgroundColor=b6e3f4',
    credentialDocUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    bio: 'Plant Pathologist specializing in early fungal leaf disease diagnosis, biological controls (Trichoderma, Pseudomonas), and precision low-cost fungicide dosage schedules to prevent pesticide residue rejection in export markets.',
    reviews: [
      {
        farmerName: 'Gurpreet Singh (Bathinda)',
        rating: 5,
        comment: 'Early blight on my tomato crop was stopped within 3 days. Her spray recommendation saved my 4-acre harvest!',
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
      {
        farmerName: 'Virender K. (Karnal)',
        rating: 5,
        comment: 'Diagnosed downy mildew from my photo upload instantly. Saved thousands on unnecessary chemical sprays.',
        date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    name: 'Er. Vikramaditya Singh',
    email: 'expert.vikram@kissansarthi.in',
    password: 'Password@123',
    role: ROLES.EXPERT,
    phone: '+91 98234 11003',
    city: 'Indore',
    state: 'Madhya Pradesh',
    isVerified: true,
    isActive: true,
    verificationStatus: 'verified',
    availableForConsultation: true,
    availability: 'online',
    consultationFee: 99,
    experienceYears: 8,
    yearsExperience: 8,
    rating: 4.8,
    reviewsCount: 29,
    totalConsultations: 95,
    qualifications: [
      'M.Tech in Agricultural Engineering (Irrigation & Drainage) — IIT Kharagpur',
      'B.Tech Agricultural Engineering — JNKVV Jabalpur',
      'Govt. Certified Micro-Irrigation Auditor',
    ],
    expertise: ['Drip Irrigation', 'Solar Pumping', 'Fertigation Venturi Systems', 'Water Harvesting'],
    specializations: ['Drip Irrigation', 'Solar Pumping', 'Fertigation Venturi Systems', 'Water Harvesting'],
    languagesSpoken: ['Hindi', 'English'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VikramSingh&backgroundColor=d1d4f9',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VikramSingh&backgroundColor=d1d4f9',
    profilePhotoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=VikramSingh&backgroundColor=d1d4f9',
    credentialDocUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    bio: 'Agricultural & Irrigation Engineer helping smallholders and orchards deploy water-efficient micro-sprinklers, automated drip lines, and solar pumping installations to cut diesel electricity costs by up to 60%.',
    reviews: [
      {
        farmerName: 'Mahendra Chouhan (Ujjain)',
        rating: 5,
        comment: 'Er. Vikram gave a detailed venturi fertigation setup plan for my soybean fields. Very practical advice.',
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    name: 'Dr. Arvind Kulkarni',
    email: 'expert.arvind@kissansarthi.in',
    password: 'Password@123',
    role: ROLES.EXPERT,
    phone: '+91 98234 11004',
    city: 'Nashik',
    state: 'Maharashtra',
    isVerified: true,
    isActive: true,
    verificationStatus: 'verified',
    availableForConsultation: true,
    availability: 'busy',
    consultationFee: 199,
    experienceYears: 16,
    yearsExperience: 16,
    rating: 4.92,
    reviewsCount: 52,
    totalConsultations: 210,
    qualifications: [
      'Ph.D. in Agronomy (Sustainable Agriculture) — Dr. BSKKV Dapoli',
      'M.Sc. Organic Agriculture — University of Kassel (Germany)',
      'Lead Auditor — NPOP & USDA-NOP Organic Standards',
    ],
    expertise: ['Organic Certification', 'Jeevamrit & Bio-fertilizers', 'Zero Budget Natural Farming', 'Crop Residue Mulching'],
    specializations: ['Organic Certification', 'Jeevamrit & Bio-fertilizers', 'Zero Budget Natural Farming', 'Crop Residue Mulching'],
    languagesSpoken: ['Hindi', 'Marathi', 'English', 'Gujarati'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ArvindKulkarni&backgroundColor=ffd5dc',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ArvindKulkarni&backgroundColor=ffd5dc',
    profilePhotoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ArvindKulkarni&backgroundColor=ffd5dc',
    credentialDocUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    bio: '16-year practitioner in chemical-free natural farming, bio-pesticide concoctions (Dashaparni ark, Neem oil), and NPOP/PGS-India organic certification audit support for farmer-producer groups.',
    reviews: [
      {
        farmerName: 'Narayan Rao (Satara)',
        rating: 5,
        comment: 'Guided our 12-member FPO step-by-step through organic certification. Highly knowledgeable and respectful.',
        date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    name: 'Pooja Deshmukh, M.Sc.',
    email: 'expert.pooja@kissansarthi.in',
    password: 'Password@123',
    role: ROLES.EXPERT,
    phone: '+91 98234 11005',
    city: 'Nagpur',
    state: 'Maharashtra',
    isVerified: true,
    isActive: true,
    verificationStatus: 'verified',
    availableForConsultation: true,
    availability: 'online',
    consultationFee: 79,
    experienceYears: 7,
    yearsExperience: 7,
    rating: 4.85,
    reviewsCount: 31,
    totalConsultations: 118,
    qualifications: [
      'M.Sc. Horticulture (Pomology & Fruit Science) — Dr. PDKV Akola',
      'B.Sc. Agriculture (Honours) — College of Agriculture, Nagpur',
      'Certificate in Post-Harvest Management — CFTRI Mysore',
    ],
    expertise: ['Horticulture', 'Citrus & Fruit Orchards', 'Post-Harvest Loss Reduction', 'Pruning Schedules'],
    specializations: ['Horticulture', 'Citrus & Fruit Orchards', 'Post-Harvest Loss Reduction', 'Pruning Schedules'],
    languagesSpoken: ['Hindi', 'Marathi', 'English'],
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PoojaDeshmukh&backgroundColor=ffdfbf',
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PoojaDeshmukh&backgroundColor=ffdfbf',
    profilePhotoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PoojaDeshmukh&backgroundColor=ffdfbf',
    credentialDocUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    bio: 'Horticulture specialist helping orchard growers optimize flowering, prevent pre-harvest fruit drop, and improve citrus sweetness index for prime mandi and direct-buyer pricing.',
    reviews: [
      {
        farmerName: 'Kishore B. (Amravati)',
        rating: 5,
        comment: 'Pooja madam recommended potassium spray and micro-pruning that prevented fruit drop in my orange grove. Excellent!',
        date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
      },
    ],
  },
];

export const seedDemoExperts = async () => {
  try {
    for (const expertData of DEMO_EXPERTS) {
      const existing = await User.findOne({ email: expertData.email });
      if (!existing) {
        await User.create(expertData);
        logger.info(`Seeded rich expert: ${expertData.name} (${expertData.email})`);
      } else {
        // Update all rich fields
        Object.assign(existing, {
          availableForConsultation: true,
          availability: expertData.availability,
          consultationFee: expertData.consultationFee,
          experienceYears: expertData.experienceYears,
          yearsExperience: expertData.yearsExperience,
          expertise: expertData.expertise,
          specializations: expertData.specializations,
          qualifications: expertData.qualifications,
          languagesSpoken: expertData.languagesSpoken,
          avatar: expertData.avatar,
          profileImage: expertData.profileImage,
          profilePhotoUrl: expertData.profilePhotoUrl,
          credentialDocUrl: expertData.credentialDocUrl,
          bio: expertData.bio,
          rating: expertData.rating,
          reviewsCount: expertData.reviewsCount,
          totalConsultations: expertData.totalConsultations,
          verificationStatus: 'verified',
          isVerified: true,
          reviews: expertData.reviews,
        });
        await existing.save();
        logger.info(`Updated expert with rich profile: ${expertData.name}`);
      }
    }
  } catch (error) {
    logger.error(`Error seeding demo experts: ${error.message}`);
  }
};
