import PDFDocument from 'pdfkit';
import cloudinary, { isCloudinaryConfigured } from '../config/cloudinary.js';
import CropRecommendation from '../models/CropRecommendation.js';
import FertilizerHistory from '../models/FertilizerHistory.js';
import logger from '../config/logger.js';
import { AppError } from '../utils/AppError.js';
import { HTTP_STATUS } from '../config/constants.js';

class PdfReportService {
  /**
   * Uploads generated buffer to Cloudinary raw storage
   */
  async uploadRawPdf(buffer, filename) {
    if (!isCloudinaryConfigured) return null;
    return new Promise((resolve) => {
      const uploadStream = cloudinary.uploader.upload_stream(
        {
          folder: 'kissansarthi/reports',
          resource_type: 'raw',
          public_id: `${filename}-${Date.now()}`,
          format: 'pdf',
        },
        (error, result) => {
          if (error) {
            logger.warn('Failed to upload PDF report to Cloudinary', error);
            resolve(null);
          } else {
            resolve(result.secure_url);
          }
        }
      );
      uploadStream.end(buffer);
    });
  }

  /**
   * Generate Crop Advisory PDF
   */
  async generateCropReport(recordId, user, res) {
    const record = await CropRecommendation.findById(recordId);
    if (!record) throw new AppError('Crop recommendation record not found', HTTP_STATUS.NOT_FOUND);

    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));

    // Pipe directly to HTTP response for instant browser download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="KissanSarthi-CropReport-${record.recommendedCrop}.pdf"`);
    doc.pipe(res);

    // Header Branding
    doc.rect(40, 40, 515, 60).fill('#1B5E20');
    doc.fillColor('#FFFFFF').fontSize(22).font('Helvetica-Bold').text('KISSANSARTHI', 55, 50);
    doc.fontSize(10).font('Helvetica').text('Smart Agriculture & Agronomy Decision Support System', 55, 76);
    doc.fontSize(9).text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 410, 76, { align: 'right' });

    doc.moveDown(3);

    // Farmer & Field Details
    doc.fillColor('#1F2937').fontSize(14).font('Helvetica-Bold').text('Farmer & Field Profile', 40, 120);
    doc.rect(40, 140, 515, 70).fillAndStroke('#F0FDF4', '#86EFAC');
    doc.fillColor('#374151').fontSize(10).font('Helvetica');
    doc.text(`Farmer Name: ${user.name || 'Registered Farmer'}`, 55, 150);
    doc.text(`Location: ${user.location || user.city || 'India'}`, 55, 168);
    doc.text(`Farm Size: ${user.farmSize ? `${user.farmSize} Acres` : 'Standard Holding'}`, 55, 186);

    doc.text(`Season: ${record.season || 'Current'}`, 320, 150);
    doc.text(`Soil Type: ${record.soilType || 'Alluvial'}`, 320, 168);
    doc.text(`Temperature: ${record.temperature ? `${record.temperature}°C` : 'Optimal'}`, 320, 186);

    // AI Crop Recommendation
    doc.fillColor('#1F2937').fontSize(14).font('Helvetica-Bold').text('AI Agronomic Recommendation', 40, 230);
    doc.rect(40, 250, 515, 100).fillAndStroke('#ECFDF5', '#10B981');
    doc.fillColor('#065F46').fontSize(18).font('Helvetica-Bold').text(`Recommended Crop: ${record.recommendedCrop}`, 55, 265);
    doc.fontSize(11).font('Helvetica').text(`Confidence Score: ${record.confidence || 88}%`, 55, 292);
    if (record.variety) doc.text(`Suggested Seed Variety: ${record.variety}`, 55, 308);
    if (record.yield) doc.text(`Estimated Average Yield: ${record.yield}`, 55, 324);

    // Agronomy & Management Tips
    doc.fillColor('#1F2937').fontSize(14).font('Helvetica-Bold').text('Field Management & Cultivation Advisory', 40, 370);
    const tips = record.tips?.length ? record.tips : [
      'Ensure proper seed treatment with bio-fungicide (Trichoderma viride @ 5g/kg seed).',
      'Maintain adequate drainage to prevent waterlogging during seedling stage.',
      'Apply basal fertilizer dose before final land harrowing.',
      'Adopt micro-irrigation (drip/sprinkler) for 30-40% water savings.'
    ];

    let y = 395;
    tips.forEach((tip, idx) => {
      doc.fillColor('#15803D').fontSize(10).font('Helvetica-Bold').text(`${idx + 1}.`, 55, y);
      doc.fillColor('#374151').font('Helvetica').text(tip, 75, y, { width: 460 });
      y += 28;
    });

    // Official Footer
    doc.rect(40, 720, 515, 45).fill('#F3F4F6');
    doc.fillColor('#6B7280').fontSize(8).font('Helvetica')
      .text('This report is generated by KissanSarthi Decision Support AI. Recommendations are based on scientific ICAR & agro-climatic datasets.', 50, 728, { align: 'center', width: 495 })
      .text('For queries, visit your nearest Krishi Vigyan Kendra (KVK). Authorized digital advisory record.', 50, 742, { align: 'center', width: 495 });

    doc.end();

    // Asynchronously save to Cloudinary if available
    doc.on('end', async () => {
      try {
        const fullBuffer = Buffer.concat(chunks);
        const url = await this.uploadRawPdf(fullBuffer, `crop-${record._id}`);
        if (url) {
          await CropRecommendation.findByIdAndUpdate(recordId, { reportUrl: url });
        }
      } catch (err) {
        logger.warn('Async PDF upload error', err);
      }
    });
  }

  /**
   * Generate Fertilizer Dosage Advisory PDF
   */
  async generateFertilizerReport(recordId, user, res) {
    const record = await FertilizerHistory.findById(recordId);
    if (!record) throw new AppError('Fertilizer record not found', HTTP_STATUS.NOT_FOUND);

    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="KissanSarthi-FertilizerPlan-${record.crop}.pdf"`);
    doc.pipe(res);

    // Header Branding
    doc.rect(40, 40, 515, 60).fill('#1E3A8A');
    doc.fillColor('#FFFFFF').fontSize(22).font('Helvetica-Bold').text('KISSANSARTHI', 55, 50);
    doc.fontSize(10).font('Helvetica').text('Balanced Nutrient Management & Fertilizer Dosage Plan', 55, 76);
    doc.fontSize(9).text(`Generated: ${new Date().toLocaleDateString('en-IN')}`, 410, 76, { align: 'right' });

    // Farmer Profile
    doc.fillColor('#1F2937').fontSize(14).font('Helvetica-Bold').text('Crop & Soil Parameters', 40, 120);
    doc.rect(40, 140, 515, 70).fillAndStroke('#EFF6FF', '#93C5FD');
    doc.fillColor('#374151').fontSize(10).font('Helvetica');
    doc.text(`Farmer: ${user.name || 'Farmer'}`, 55, 150);
    doc.text(`Crop: ${record.crop}`, 55, 168);
    doc.text(`Growth Stage: ${record.stage}`, 55, 186);

    doc.text(`Soil pH: ${record.soilPH || '6.5'}`, 320, 150);
    doc.text(`Target Deficiency: ${record.deficiency || 'Nitrogen'}`, 320, 168);
    doc.text(`Estimated Acreage: ${user.farmSize || 1} Acre(s)`, 320, 186);

    // Dosage Table
    doc.fillColor('#1F2937').fontSize(14).font('Helvetica-Bold').text('Recommended Fertilizer Formulation', 40, 230);
    doc.rect(40, 250, 515, 90).fillAndStroke('#F8FAFC', '#CBD5E1');
    doc.fillColor('#1E3A8A').fontSize(12).font('Helvetica-Bold').text(`Primary Recommendation: ${record.recommendation?.primary || 'Urea + DAP'}`, 55, 265);
    doc.fillColor('#374151').fontSize(10).font('Helvetica');
    doc.text(`Dosage: ${record.recommendation?.dose || '50 kg / acre'}`, 55, 285);
    doc.text(`Secondary Nutrient: ${record.recommendation?.secondary || 'Zinc Sulphate @ 5 kg / acre'}`, 55, 303);
    doc.text(`Estimated Cost: ${record.recommendation?.cost || '₹850 - ₹1,100 per acre'}`, 55, 321);

    // Split Application Timeline
    doc.fillColor('#1F2937').fontSize(14).font('Helvetica-Bold').text('Application Schedule', 40, 360);
    const scheduleItems = [
      { stage: 'Basal Dose (At Sowing)', desc: 'Full dose of Phosphorus (DAP) + Potash (MOP) + 1/3rd Nitrogen (Urea)' },
      { stage: 'First Top Dressing (20-30 Days)', desc: 'Apply 1/3rd Nitrogen (Urea) with first post-sowing irrigation' },
      { stage: 'Second Top Dressing (45-60 Days)', desc: 'Remaining 1/3rd Nitrogen (Urea) during active tillering / pre-flowering' },
    ];

    let y = 385;
    scheduleItems.forEach((item) => {
      doc.rect(40, y, 515, 36).fillAndStroke('#F0FDF4', '#BBF7D0');
      doc.fillColor('#166534').fontSize(10).font('Helvetica-Bold').text(item.stage, 55, y + 6);
      doc.fillColor('#374151').fontSize(9).font('Helvetica').text(item.desc, 55, y + 20);
      y += 44;
    });

    // Safety & Environmental Caution
    doc.rect(40, 530, 515, 55).fillAndStroke('#FEF3C7', '#FCD34D');
    doc.fillColor('#92400E').fontSize(10).font('Helvetica-Bold').text('Cautionary Notes for Soil Health:', 55, 540);
    doc.fontSize(8.5).font('Helvetica')
      .text('• Do not broadcast fertilizer under direct strong sunlight. Always apply when soil has optimum moisture.', 55, 555)
      .text('• Consider adding 2 tons of Farm Yard Manure (FYM) per acre annually to maintain soil organic carbon.', 55, 567);

    // Official Footer
    doc.rect(40, 720, 515, 45).fill('#F3F4F6');
    doc.fillColor('#6B7280').fontSize(8).font('Helvetica')
      .text('Issued by KissanSarthi Agronomy Module. Calibrated for Indian soil agro-climatic conditions.', 50, 728, { align: 'center', width: 495 })
      .text('Consult your district soil testing laboratory for site-specific micro-nutrient calibration.', 50, 742, { align: 'center', width: 495 });

    doc.end();

    doc.on('end', async () => {
      try {
        const fullBuffer = Buffer.concat(chunks);
        const url = await this.uploadRawPdf(fullBuffer, `fertilizer-${record._id}`);
        if (url) {
          await FertilizerHistory.findByIdAndUpdate(recordId, { reportUrl: url });
        }
      } catch (err) {
        logger.warn('Async fertilizer PDF upload error', err);
      }
    });
  }
}

export default new PdfReportService();
