import toast from 'react-hot-toast';

/**
 * Dynamic loader for Razorpay Checkout script (if not already loaded via index.html)
 */
export const loadRazorpayScript = () => {
  return new Promise((resolve) => {
    if (window.Razorpay) {
      resolve(true);
      return;
    }
    const existing = document.querySelector('script[src*="checkout.razorpay.com"]');
    if (existing) {
      existing.addEventListener('load', () => resolve(true));
      existing.addEventListener('error', () => resolve(false));
      return;
    }
    const script = document.createElement('script');
    script.src = 'https://checkout.razorpay.com/v1/checkout.js';
    script.async = true;
    script.onload = () => resolve(true);
    script.onerror = () => resolve(false);
    document.body.appendChild(script);
  });
};

/**
 * Open the real Razorpay Checkout widget.
 *
 * @param {Object} options
 * @param {string} options.keyId - Razorpay public key ID
 * @param {string} options.orderId - Razorpay order ID
 * @param {number} options.amount - Amount in paise (e.g. 4900 for ₹49)
 * @param {string} options.currency - Currency (default 'INR')
 * @param {string} options.name - Title in checkout modal
 * @param {string} options.description - Subtitle/description
 * @param {Object} options.prefill - { name, email, contact }
 * @param {Function} options.onSuccess - Callback on payment success ({ razorpayOrderId, razorpayPaymentId, razorpaySignature })
 * @param {Function} options.onError - Callback on payment failure/error
 * @param {Function} options.onDismiss - Callback when user closes checkout
 */
export const openRazorpayCheckout = async ({
  keyId,
  orderId,
  amount,
  currency = 'INR',
  name = 'KissanSarthi',
  description = 'Agricultural Services & Membership',
  prefill = {},
  onSuccess,
  onError,
  onDismiss,
}) => {
  const scriptLoaded = await loadRazorpayScript();

  if (!scriptLoaded || !window.Razorpay) {
    const errMsg = 'Razorpay Checkout script could not be loaded. Please check your internet connection.';
    toast.error(errMsg);
    onError?.(new Error(errMsg));
    return;
  }

  // Resolve active public key
  const activeKeyId =
    keyId ||
    import.meta.env.VITE_RAZORPAY_KEY_ID ||
    'rzp_test_1DP5mmOlF5G5ag';

  const options = {
    key: activeKeyId,
    amount,
    currency,
    name,
    description,
    image: 'https://cdn-icons-png.flaticon.com/512/1888/1888934.png',
    handler: function (response) {
      if (!response.razorpay_payment_id) {
        toast.error('Payment response missing payment ID');
        onError?.(new Error('Invalid payment response'));
        return;
      }
      onSuccess?.({
        razorpayOrderId: response.razorpay_order_id || orderId,
        razorpayPaymentId: response.razorpay_payment_id,
        razorpaySignature: response.razorpay_signature,
      });
    },
    prefill: {
      name: prefill.name || '',
      email: prefill.email || '',
      contact: prefill.phone || prefill.contact || '',
    },
    notes: {
      platform: 'KissanSarthi Agri Portal',
    },
    theme: {
      color: '#2E7D32', // Forest / Agro Green
    },
    modal: {
      ondismiss: function () {
        toast('Payment window closed', { icon: 'ℹ️' });
        onDismiss?.();
      },
      escape: true,
      backdropclose: false,
    },
  };

  // Only pass order_id if it was generated by Razorpay's API
  if (orderId && !orderId.startsWith('order_sim_')) {
    options.order_id = orderId;
  }

  try {
    const rzp = new window.Razorpay(options);

    rzp.on('payment.failed', function (response) {
      console.warn('Razorpay payment failed callback:', response.error);
      const failReason = response.error?.description || response.error?.reason || 'Transaction could not be completed';
      toast.error(`Payment Failed: ${failReason}`);
      onError?.(response.error);
    });

    rzp.open();
  } catch (err) {
    console.error('Failed to open Razorpay modal:', err);
    toast.error(err.message || 'Could not open payment checkout');
    onError?.(err);
  }
};
